### PR TITLE
#67 public static FOREIGN_KEY_SUFFIX  non-final

### LINKED ISSUE #67: Changing name of association column name
In app I am working on we already have tables where columns are named in camel case (for example "userId"). And dont want to add column name in mapping for each association in domain. 
Currently, default behavior for naming columns for associations is just to add "_id" which is set [here](https://github.com/grails/gorm-hibernate5/blob/master/grails-datastore-gorm-hibernate5/src/main/groovy/org/grails/orm/hibernate/cfg/GrailsDomainBinder.java#L82) 
So is it possible to make `FOREIGN_KEY_SUFFIX`  configurable, that will be great, or at least not `final protected` so it can be changed?

### PR DESCRIPTION
**Pull request by basejump**
closes grails/grails-data-mapping#2006

### CODE REVIEW

**Comment by basejump** [comment]
NAMING_STRATEGIES  is a public static and I know making FOREIGN_KEY_SUFFIX public static as well is not ideal but any chance we can get the pull request merged so we can overrride the _id globally?

**Comment by graemerocher** [comment]
this change seems problematic to me as it would prevent having different sessions factories with different strategies

**Comment by basejump** [comment]
Thanks for feedback Graeme. Not sure I totally follow? Currently NAMING_STRATEGIES is public which allows it to be be set. The problem we face is the the FOREIGN_KEY_SUFFIX is a protected final for "_id" and can't be modified. How would setting that to public "non-final" effect the sessions factories?

**Comment by basejump** [comment]
@graemerocher would love to get the ability to change the FOREIGN_KEY_SUFFIX into core here. What if we remove the _ prefix and made it Id when the `naming_strategy: org.hibernate.cfg.DefaultNamingStrategy` which is what we are ultimately after. DefaultNamingStrategy as you know makes the column names camelcase to match the fields. So in this case it would make sense no to end the foreign keys with "_id". Or point us in the right direction on a better strategy here and we can fix PR to make this configurable in some fashion. Thanks

**Comment by graemerocher** [comment]
the correct change is to find where `FOREIGN_KEY_SUFFIX` is used and extract that into a method that can be overridden. I don't think making static constants mutable is the ideal fix here.

**Pull request closed without merging**
